
spring:
  datasource:
    url: jdbc:mysql:///student_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
dubbo:
  registry:
    address: zookeeper://192.168.114.168:2181
  application:
    name: stu_service
  protocol:
    #配置提供者的端口，-1表示自行查找一个可用的端口
    port: -1
  consumer:
    check: false