spring:
  datasource:
    url: jdbc:mysql:///classes_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
dubbo:
  application:
    name: classes_service
  registry:
    address: zookeeper://192.168.114.168:2181